### ISSUE TITLE
Erroneous PWM

### ISSUE THREAD

**Issue by andrey-gvrd** [adafruit/Adafruit-TLC5947-PCB#2]
I'm having issues with erroneous PWM outputs. Happens only when the PWM channel is being continuously updated.

In this image the PWM value is being slowly changed, but there's a wrong value circled:
![20190822_131111 (3)_LI](https://user-images.githubusercontent.com/5842980/63552179-da47ad80-c4eb-11e9-8ad0-d5350902c6a4.jpg)

Even if I increase the delay between writes to 100ms (which is already too much for my use case), the problem remains.

Here's the code:
```
#include "Adafruit_TLC5947.h"

#define NUM_TLC5974 1

#define CLOCK_PIN 6
#define LATCH_PIN 8
#define DATA_PIN  9

Adafruit_TLC5947 tlc = Adafruit_TLC5947(NUM_TLC5974, CLOCK_PIN, DATA_PIN, LATCH_PIN);

void setup() {
  tlc.begin();
}

#define MIN 3000
#define MAX 4095
#define STEP 10

void loop() {
  for (int32_t i = MIN; i < MAX; i += STEP) {
    tlc.setPWM(1, i);
    tlc.write();
    delay(10);
  }
  delay(500);
  for (int32_t i = MAX; i > MIN; i -= STEP) {
    tlc.setPWM(1, i);
    tlc.write();
    delay(10);
  }
  delay(500);
}
```

**Comment by ladyada** [comment]
not much you can do about it, its cause the chip is updating the PWM at the same time as outputting, and you get an overlap (rarely). its in hardware.

**Comment by andrey-gvrd** [comment]
Ok, that's what I thought.

This seems like a deal-breaker for most applications where the PWM outputs are not constant -- dimming looks absolutely horrible. Am I wrong?

I'm finding some combinations of `STEP` and `delay(T)` to be particularly terrible.

STEP 100 and `delay(10)` are OK.

**Comment by andrey-gvrd** [comment]
Ok, that's what I thought.

I'm kinda surprised it's implemented this way -- wouldn't it make more sense to update the PWM output at the end of the period instead of in the middle?

I'm finding some tie between STEP and `delay(T)` and the resulting flicker when dimming. Probably some kind of aliasing effect?

> STEP 100 and delay(10) -- OK.
> STEP 25 and delay(10) -- terrible.
> STEP 25 and delay(1) -- OK.
> STEP 10 and delay(1) -- terrible.
> STEP 5 and delay(1) -- terrible.

Kinda off topic, but does your PCA9685 have the same issue?

**Comment by andrey-gvrd** [comment]
Also probably unrelated to this topic, but it says [here](https://learn.adafruit.com/tlc5947-tlc59711-pwm-led-driver-breakout?view=all) that "The TLC5947 has a fixed PWM frequency in the high megahertz range which is good for driving LEDs." but I'm seeing a little over a a kilohertz on the output.

**Comment by ladyada** [comment]
I think PC9685 does not, or at least we've not seen it. maybe that's what blank input is for, so you can disable all LEDs, then shift in the new values and re-enable? its been many years since we used this chip :D
https://cdn-shop.adafruit.com/datasheets/tlc5947.pdf
has all info, there's up to 15mhz SPI data rate. that's not the LED itself - removed that text, the guide author was confused. the LEDs may not be that high (its actually not even specified int he datasheet!)

**Comment by andrey-gvrd** [comment]
PCA9685 works perfectly.
